### ISSUE TITLE
Applicability of Linear Color Homography for Locally Adjusted Images

### ISSUE THREAD

**Issue by a2108870** [hangong/ch#2]
Hello,

Thank you for your valuable work. I read in your paper about the simple linear color homography mapping for color transfer in image editing. As we know, for photographers, image editing might involve a combination of multiple local regions adjustments. With that in mind, I was wondering if the method you mentioned in your paper can be applied to map the colors of an image to another whose colors have been locally adjusted?

Thank you for your time and assistance.

**Comment by hangong** [comment]
Hello! Thanks for your interest. The quick answer is no. Color homography
is a global color transform. But some local tone changes might work.

Han

**Comment by a2108870** [comment]
Thank you for your advice. I will consider introducing an incremental network for local color changes after global correction.
